name = "InverseNpde"
uuid = "00c7dfff-8570-4b1d-b22c-9533dc130a70"
version = "0.1.0"
authors = ["Research Team <team@institute.edu>"]

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCUDA = "d0bbae9a-e099-4d5b-a835-1c6931763bda"
NeuralPDE = "315f7962-48a3-4962-8226-d0f33b1235f0"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TensorBoardLogger = "899adc3e-224a-11e9-021f-63837185c80f"

[compat]
CUDA = "5.9.5"
ComponentArrays = "0.15.30"
LineSearches = "7.5.1"
Lux = "1.21.1"
LuxCUDA = "0.3.4"
NeuralPDE = "5.20.0"
Optimization = "4.8.0"
OptimizationOptimJL = "0.4.5"
OptimizationOptimisers = "0.3.11"
Plots = "1.41.3"
Printf = "1.11.0"
ProgressBars = "1.5.1"
Random = "1.11.0"
TensorBoardLogger = "0.1.26"
