name = "InverseNpde"
uuid = "00c7dfff-8570-4b1d-b22c-9533dc130a70"
authors = ["Research Team <team@institute.edu>"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCUDA = "d0bbae9a-e099-4d5b-a835-1c6931763bda"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NeuralPDE = "315f7962-48a3-4962-8226-d0f33b1235f0"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
OpenSSL_jll = "458c3c95-2e84-50aa-8efc-19380b2a3a95"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TensorBoardLogger = "899adc3e-224a-11e9-021f-63837185c80f"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
CUDA = "5.9.5"
CairoMakie = "0.15.8"
ChainRulesCore = "1.26.0"
ComponentArrays = "0.15.30"
Dierckx = "0.5.4"
Distributions = "0.25.122"
GLMakie = "0.13.8"
GeometryBasics = "0.5.10"
Integrals = "4.10.0"
JLD2 = "0.6.3"
LineSearches = "7.5.1"
Lux = "1.21.1"
LuxCUDA = "0.3.4"
Makie = "0.24.8"
ModelingToolkit = "9.35.0"
NeuralPDE = "5.20.0"
Observables = "0.5.5"
OpenSSL_jll = "3.5.4"
Optimization = "4.8.0"
OptimizationOptimJL = "0.4.5"
OptimizationOptimisers = "0.3.11"
Parameters = "0.12.3"
Plots = "1.41.3"
ProgressBars = "1.5.1"
PythonCall = "0.9.31"
Reexport = "1.2.2"
Statistics = "1.11.1"
Symbolics = "6.58.0"
TensorBoardLogger = "0.1.26"
Zygote = "0.7.10"
